-- 1. Nhân viên 
CREATE TABLE NHANVIEN (
    MANV CHAR(3) PRIMARY KEY,
    HONV NVARCHAR2(15),
    TENLOT NVARCHAR2(15),
    TENNV NVARCHAR2(15),
    NGAYSINH DATE,
    DCHI NVARCHAR2(50),
    PHAI NVARCHAR2(3),
    LUONG NUMBER(10,2),
    MA_NQL CHAR(3), 
    PHG NUMBER(2)   
);

-- 2. Ph?ng ban 
CREATE TABLE PHONGBAN (
    MAPHG NUMBER(2) PRIMARY KEY,
    TENPHG NVARCHAR2(30) NOT NULL,
    TRPHG CHAR(3), 
    NG_NHANCHUC DATE,
    FOREIGN KEY (TRPHG) REFERENCES NHANVIEN(MANV)
);

-- 3. Khóa ngo?i cho b?ng NHANVIEN
ALTER TABLE NHANVIEN ADD FOREIGN KEY (PHG) REFERENCES PHONGBAN(MAPHG);
ALTER TABLE NHANVIEN ADD FOREIGN KEY (MA_NQL) REFERENCES NHANVIEN(MANV);

-- 4. Ð?a ði?m ph?ng ban
CREATE TABLE DIADIEM_PHG (
    MAPHG NUMBER(2),
    DIADIEM NVARCHAR2(30),
    PRIMARY KEY (MAPHG, DIADIEM),
    FOREIGN KEY (MAPHG) REFERENCES PHONGBAN(MAPHG)
);

-- 5.Ð? án
CREATE TABLE DEAN (
    MADA CHAR(3) PRIMARY KEY,
    TENDA NVARCHAR2(50) NOT NULL,
    DDIEM_DA NVARCHAR2(30),
    PHONG NUMBER(2),
    FOREIGN KEY (PHONG) REFERENCES PHONGBAN(MAPHG)
);

-- 6.Phân công
CREATE TABLE PHANCONG (
    MA_NVIEN CHAR(3),
    MADA CHAR(3),
    THOIGIAN NUMBER(5,1),
    PRIMARY KEY (MA_NVIEN, MADA),
    FOREIGN KEY (MA_NVIEN) REFERENCES NHANVIEN(MANV),
    FOREIGN KEY (MADA) REFERENCES DEAN(MADA)
);

-- 7. Thân nhân
CREATE TABLE THANNHAN (
    MA_NVIEN CHAR(3),
    TENTN NVARCHAR2(20),
    PHAI NVARCHAR2(3),
    NGAYSINH DATE,
    QUANHE NVARCHAR2(15),
    PRIMARY KEY (MA_NVIEN, TENTN),
    FOREIGN KEY (MA_NVIEN) REFERENCES NHANVIEN(MANV)
);

-- 1. Thêm 2 Ph?ng ban 
INSERT INTO PHONGBAN (MAPHG, TENPHG, TRPHG, NG_NHANCHUC) 
VALUES (1, N'Nghiên c?u', NULL, TO_DATE('01/01/2020', 'DD/MM/YYYY'));

INSERT INTO PHONGBAN (MAPHG, TENPHG, TRPHG, NG_NHANCHUC) 
VALUES (2, N'Ði?u hành', NULL, TO_DATE('15/05/2021', 'DD/MM/YYYY'));

-- 2. Thêm 2 Nhân viên 
-- Nhân viên 1 
INSERT INTO NHANVIEN (MANV, HONV, TENLOT, TENNV, NGAYSINH, DCHI, PHAI, LUONG, MA_NQL, PHG)
VALUES ('001', N'Nguy?n', N'Vãn', N'An', TO_DATE('10/05/1980', 'DD/MM/YYYY'), N'TP.HCM', N'Nam', 25000, NULL, 2);

-- Nhân viên 2 
INSERT INTO NHANVIEN (MANV, HONV, TENLOT, TENNV, NGAYSINH, DCHI, PHAI, LUONG, MA_NQL, PHG)
VALUES ('002', N'Tr?n', N'Th?', N'B?nh', TO_DATE('20/10/1990', 'DD/MM/YYYY'), N'B?nh Dýõng', N'N?', 15000, '001', 1);

-- 3. B? nhi?m Trý?ng ph?ng cho 2 ph?ng ban ? trên
UPDATE PHONGBAN SET TRPHG = '002' WHERE MAPHG = 1; -- Tr?n Th? B?nh làm trý?ng ph?ng Nghiên c?u
UPDATE PHONGBAN SET TRPHG = '001' WHERE MAPHG = 2; -- Nguy?n Vãn An làm trý?ng ph?ng Ði?u hành

-- 4. B?ng Ð?a ði?m ph?ng ban
INSERT INTO DIADIEM_PHG (MAPHG, DIADIEM) VALUES (1, N'Hà N?i');
INSERT INTO DIADIEM_PHG (MAPHG, DIADIEM) VALUES (2, N'TP.HCM');

-- 5. B?ng Ð? án
INSERT INTO DEAN (MADA, TENDA, DDIEM_DA, PHONG) 
VALUES ('DA1', N'S?n ph?m X', N'Hà N?i', 1);

INSERT INTO DEAN (MADA, TENDA, DDIEM_DA, PHONG) 
VALUES ('DA2', N'M? r?ng th? trý?ng', N'TP.HCM', 2);

-- 6. B?ng Phân công (Ai làm ð? án nào, th?i gian bao lâu)
INSERT INTO PHANCONG (MA_NVIEN, MADA, THOIGIAN) VALUES ('001', 'DA2', 20.5);
INSERT INTO PHANCONG (MA_NVIEN, MADA, THOIGIAN) VALUES ('002', 'DA1', 15.0);

-- 7. B?ng Thân nhân 
INSERT INTO THANNHAN (MA_NVIEN, TENTN, PHAI, NGAYSINH, QUANHE) 
VALUES ('001', N'Nguy?n Vãn Bé', N'Nam', TO_DATE('01/01/2010', 'DD/MM/YYYY'), N'Con trai');

INSERT INTO THANNHAN (MA_NVIEN, TENTN, PHAI, NGAYSINH, QUANHE) 
VALUES ('002', N'Lê Th? Châu', N'N?', TO_DATE('05/05/2015', 'DD/MM/YYYY'), N'Con gái');

COMMIT;

