-- 1. Danh m?c Khoa 
CREATE TABLE DMKHOA (
    MAKHOA CHAR(2) PRIMARY KEY,
    TENKHOA NVARCHAR2(30)
);

-- 2. Danh m?c Môn h?c 
CREATE TABLE DMMH (
    MAMH CHAR(2) PRIMARY KEY,
    TENMH NVARCHAR2(35),
    SOTIET NUMBER(3)
);

-- 3. Danh m?c Sinh viên 
CREATE TABLE DMSV (
    MASV CHAR(3) PRIMARY KEY,
    HOSV NVARCHAR2(30),
    TENSV NVARCHAR2(10),
    PHAI NVARCHAR2(3),
    NGAYSINH DATE,
    NOISINH NVARCHAR2(25),
    MAKH CHAR(2),
    HOCBONG NUMBER(10,0),
    FOREIGN KEY (MAKH) REFERENCES DMKHOA(MAKHOA)
);

-- 4. K?t qu?
CREATE TABLE KETQUA (
    MASV CHAR(3),
    MAMH CHAR(2),
    PRIMARY KEY (MASV, MAMH),
    FOREIGN KEY (MASV) REFERENCES DMSV(MASV),
    FOREIGN KEY (MAMH) REFERENCES DMMH(MAMH)
);
-- 1. Thêm 2 Khoa vào b?ng DMKHOA
INSERT INTO DMKHOA (MAKHOA, TENKHOA) VALUES ('CN', N'Công ngh? thông tin');
INSERT INTO DMKHOA (MAKHOA, TENKHOA) VALUES ('KT', N'K? toán');

-- 2. Thêm 2 Môn h?c vào b?ng DMMH
INSERT INTO DMMH (MAMH, TENMH, SOTIET) VALUES ('CS', N'Cõ s? d? li?u', 45);
INSERT INTO DMMH (MAMH, TENMH, SOTIET) VALUES ('LT', N'L?p tr?nh cãn b?n', 60);

-- 3. Thêm 2 Sinh viên vào b?ng DMSV 
INSERT INTO DMSV (MASV, HOSV, TENSV, PHAI, NGAYSINH, NOISINH, MAKH, HOCBONG) 
VALUES ('S01', N'Nguy?n Vãn', N'An', N'Nam', TO_DATE('15/02/2003', 'DD/MM/YYYY'), N'TP.HCM', 'CN', 1500000);

INSERT INTO DMSV (MASV, HOSV, TENSV, PHAI, NGAYSINH, NOISINH, MAKH, HOCBONG) 
VALUES ('S02', N'Tr?n Th?', N'B?nh', N'N?', TO_DATE('20/10/2003', 'DD/MM/YYYY'), N'Ð?ng Nai', 'KT', 0);

-- 4. Thêm 2 K?t qu? h?c t?p vào b?ng KETQUA 
INSERT INTO KETQUA (MASV, MAMH) VALUES ('S01', 'CS');
INSERT INTO KETQUA (MASV, MAMH) VALUES ('S02', 'LT');

COMMIT;